FROM selenium/node-chrome:${IMAGE_VERSION}
MAINTAINER Chris Garrett (https://github.com/chris-garrett/docker-selenium-node-chrome)
LABEL description="Selenium Node Chrome image ${IMAGE_VERSION}"
RUN mkdir /home/seluser/downloads
